### ISSUE TITLE
I need your help please

### ISSUE THREAD

**Issue by cavl3108** [TobiasVanDyk/STM32F411-PCM5102A-24bit-USB-Audio-DAC#1]
Hello, what is the possibility that you can help me set up or develop a code based on this, even if it is necessary to pay you, I need, based on the black pill card and the pcm5102, with the USB audio protocol to create a kind of crossover and digital graphic equalizer where it makes use of the DSP core integrated into the card and the control of the band gains is carried out through a graphic interface, either digital through an Android application or an analog interface, please I need your help.

**Comment by TobiasVanDyk** [comment]
Hi

The code to do all of that is already available if you use another ARM-based MCU namely an H7-based [Teensy 4x](https://www.pjrc.com/) - have you heard about it?

Recent STM examples seems to move away from audio DSP's

Please see the [Teensy Audio System Design Tool](https://www.pjrc.com/teensy/gui/ ) and the [Teensy forum](https://forum.pjrc.com/)

**Comment by TobiasVanDyk** [comment]
If you post the following on the Teensy forum you will get a good reaction from the members there:

_Hello, I am new to the Teensy world and before I purchase any, I would like to know if what I need already exist or is possible?_

_I need help to set up or develop code based on the Teensy 4x and a PCM5102, with the USB audio protocol to create a kind of crossover and digital graphic equalizer where it makes use of the DSP core integrated into the card and the control of the band gains is carried out through a graphic interface, either digital through an Android application or an analog interface._
