### ISSUE TITLE
master clock frequency

### ISSUE THREAD

**Issue by Jente105** [TobiasVanDyk/STM32F411-PCM5102A-24bit-USB-Audio-DAC#3]
firstly, thanks for your work on this subject. 
I was looking to replace the PCM5102a with a better dac. I noticed that the STM32F411xE configuration could provide the masterclock. what would the frequency at the rated sample frequencies(44.1, 48 and 96 kHz) of your firmware be when masterclock generation is enabled? 

thanks,

**Comment by TobiasVanDyk** [comment]
Hi

Yikes those calculations are above my paygrade I’m afraid

The best is to post your query on the origin of the source code that I am using which is
https://github.com/har-in-air/STM32F411_USB_AUDIO_DAC
and
https://github.com/dragonman225/stm32f469-usbaudio

If you get to a working configuration with an external i2s clock please let me know the details..

Best wishes
Tobias van Dyk



From: Jente105 ***@***.***>
Sent: Wednesday, 26 June 2024 14:11
To: TobiasVanDyk/STM32F411-PCM5102A-24bit-USB-Audio-DAC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TobiasVanDyk/STM32F411-PCM5102A-24bit-USB-Audio-DAC] master clock frequency (Issue #3)


firstly, thanks for your work on this subject.
I was looking to replace the PCM5102a with a better dac. I noticed that the STM32F411xE configuration could provide the masterclock. what would the frequency at the rated sample frequencies(44.1, 48 and 96 kHz) of your firmware be when masterclock generation is enabled?

thanks,

**Comment by TobiasVanDyk** [comment]
Hi

I attach the SCK frequencies from the datasheet page 24

Best wishes
TvD

From: Jente105 ***@***.***>
Sent: Wednesday, 26 June 2024 14:11
To: TobiasVanDyk/STM32F411-PCM5102A-24bit-USB-Audio-DAC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TobiasVanDyk/STM32F411-PCM5102A-24bit-USB-Audio-DAC] master clock frequency (Issue #3)


firstly, thanks for your work on this subject.
I was looking to replace the PCM5102a with a better dac. I noticed that the STM32F411xE configuration could provide the masterclock. what would the frequency at the rated sample frequencies(44.1, 48 and 96 kHz) of your firmware be when masterclock generation is enabled?

thanks,

**Comment by TobiasVanDyk** [comment]
![pcm5102-SCK](https://github.com/TobiasVanDyk/STM32F411-PCM5102A-24bit-USB-Audio-DAC/assets/22213123/55afcf81-99da-4e2f-9342-b3ca424398d4)

**Comment by TobiasVanDyk** [comment]
Also check [**issue #26 master clock frequency for 4 wire i2s**](https://github.com/har-in-air/STM32F411_USB_AUDIO_DAC/issues/)
*"As per reference manual RM0383 for F411, when MCLK is enabled, MCLK = 256 x Fs (page 585)I've added a comment in the Makefile."*
